[build]
  command = "npm run setup && mkdir -p dist/components/claude-artifacts && cp -r src/components/claude-artifacts/* dist/components/claude-artifacts/ && npm run build"
  publish = "dist"

# Optional: Configure Netlify dev for local testing
[dev]
  command = "npm run dev"
  port = 4321
  framework = "astro"