import React from 'react';
import { Routes, Route, Link, NavLink } from 'react-router-dom';
import ArtifactBrowser from './components/ArtifactBrowser';

// Import static page components for each artifact
import BarChartPage from './pages/artifacts/BarChart';
import DataTablePage from './pages/artifacts/DataTable';
import DataTableTooPage from './pages/artifacts/DataTableToo';

function App() {
  return (
    <div className="app">
      <header className="mb-8 text-center">
        <h1 className="text-3xl font-bold">Claude Artifacts Host</h1>
        <p className="text-gray-600">A system for hosting and displaying React components generated by Claude</p>
        <nav className="mt-4">
          <NavLink 
            to="/" 
            className={({ isActive }) => 
              isActive 
                ? "mx-2 px-4 py-2 bg-blue-500 text-white rounded" 
                : "mx-2 px-4 py-2 bg-gray-200 rounded hover:bg-gray-300"
            }
            end
          >
            Artifacts Index
          </NavLink>
        </nav>
      </header>
      
      <main>
        <Routes>
          <Route path="/" element={<ArtifactBrowser />} />
          <Route path="/artifact/barchart" element={<BarChartPage />} />
          <Route path="/artifact/datatable" element={<DataTablePage />} />
          <Route path="/artifact/datatabletoo" element={<DataTableTooPage />} />
        </Routes>
      </main>
      
      <footer className="mt-12 pt-4 border-t text-center text-gray-500 text-sm">
        <p>Note: This is a basic implementation. For production use, consider security implications.</p>
      </footer>
    </div>
  );
}

export default App;