/**
 * Configuration options for the Claude AI Artifacts Showcase
 * Edit these values to customize your showcase site
 */

export const siteConfig = {
  // Basic site information
  title: "Claude AI Artifacts Showcase",
  description: "A showcase of interactive components generated by Claude AI",
  
  // Site appearance
  theme: {
    primaryColor: "#6A5ACD", // SlateBlue
    secondaryColor: "#4B0082", // Indigo
    accentColor: "#9370DB", // MediumPurple
    backgroundColor: "#F8F9FA",
    darkMode: false, // Enable/disable dark mode option
  },
  
  // Navigation settings
  navigation: {
    showHomeLink: true,
    showAllArtifactsLink: true,
    showCategoriesMenu: true,
    showSearchBar: true,
  },
  
  // Artifact display settings
  artifacts: {
    cardsPerPage: 9,
    showCreationDate: true,
    showDescription: true,
    showComponentPreview: true,
    sortBy: "date", // Options: "date", "name", "category"
    sortDirection: "desc", // Options: "asc", "desc"
  },
  
  // Individual artifact page settings
  artifactPage: {
    showSourceCode: true,
    showCopyButton: true,
    showFullScreenButton: true,
    showBackToGalleryButton: true,
  },
  
  // Footer information
  footer: {
    showFooter: true,
    copyrightText: `© ${new Date().getFullYear()} dcdigit`,
    showSocialLinks: false,
    socialLinks: [
      { name: "GitHub", url: "https://github.com/" },
      { name: "Mastodon", url: "https://mastodon.com/" },
    ],
  },
  
  // Advanced settings
  advanced: {
    enablePWA: false, // Enable/disable Progressive Web App features
    analyticsID: "", // Add your Google Analytics ID here
    artifactsDirectory: "src/components/claude-artifacts", // Path to artifacts directory
  }
};

/**
 * Category definitions for artifacts
 * Add or modify categories as needed
 */
export const categories = [
  {
    id: "ui-components",
    name: "UI Components",
    description: "Basic user interface components like buttons, cards, and inputs",
  },
  {
    id: "data-visualization",
    name: "Data Visualization",
    description: "Charts, graphs and other data visualization components",
  },
  {
    id: "interactive-tools",
    name: "Interactive Tools",
    description: "Complex interactive components with business logic",
  },
  {
    id: "games",
    name: "Games",
    description: "Simple games and interactive entertainment components",
  },
];

export default siteConfig;

